### ISSUE TITLE
Cannot parse 4.11+ replays

### ISSUE THREAD

**Issue by Cyberblasta** [ggtracker/sc2reader#108]
File "C:\Users\cyber\AppData\Local\Programs\Python\Python38\lib\site-packages\sc2reader\decoders.py", line 111, in read_string
    return self.read_bytes(count).decode(encoding)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 27: invalid start byte

**Comment by StoicLoofah** [comment]
Thanks for reporting this issue. Can you also share the replay that is causing problems?

**Comment by Cyberblasta** [comment]
Basically it's every replay after 4.11 i have. For example [this one](http://sc2replaystats.com/replay/12566586).

**Comment by Talv** [comment]
I believe this was fixed in a31452715acb9fae1739703631f7abbc7afec30d

How did you install `sc2reader`? From PyPi? If so, you'll need to install from Git master. [Package published on PyPi is out of date](https://pypi.org/project/sc2reader/#history).

If you're using `pip`, this will do:
`pip install --user --force-reinstall git+https://github.com/ggtracker/sc2reader.git`

**Comment by Cyberblasta** [comment]
Thank you for what you doing and happy new year!
