### ISSUE TITLE
Is it possible to implement encode and save?

### ISSUE THREAD

**Issue by linchenrr** [ggtracker/sc2reader#116]
There are sometimes message events(other players send message) in the replay files. If we can remove them would be better for recoding video.
I don't know is there any way to encode the struct  from sc2reader.load_replay back to .replay Binary?

**Comment by StoicLoofah** [comment]
I'm unaware of any functionality like this in sc2reader, though perhaps there are other methods or tools for doing it. I'll leave this comment open if anyone else has ideas, but I will note that this task seems too large to undertake as currently defined.

**Comment by Talv** [comment]
SC2Replay file is an MPQ archive, there are multiple files inside, describing different aspects of the game. The chat history is in `replay.message.events`. This is an event stream that contains no gameplay relevant data (https://github.com/Blizzard/s2protocol/blob/ea1fe843b46ee5589a86054361d8d13e49483790/s2protocol/versions/protocol77661.py#L348-L354). I believe this file could be simply removed, and SC2 client should still allow to view the replay. Just without chat history, minimap pings etc.

If however I'm wrong about it, then another solution would be replacing this file with a one from another replay, which has no chat history. It might be important to use the same version. And preferably with the same amount of participating players.

In regards to re-encoding replays, yes it is possible. But it's out of the scope `sc2reader` - since it's a reader :) But Blizzard has released scripts for encoding in their repo: https://github.com/Blizzard/s2protocol/blob/ea1fe843b46ee5589a86054361d8d13e49483790/s2protocol/encoders.py
It lacks documentation/code examples, but this is the way to go about this. And this is also how Deepmind anonymized replay packs with AlphaStar from ladder.

Also, if all you need is to hide the chat history. Then there's yet another method! :) You could modify the observer interface, and hide the part of the UI responsible for displaying messages.

**Comment by linchenrr** [comment]
> SC2Replay file is an MPQ archive, there are multiple files inside, describing different aspects of the game. The chat history is in `replay.message.events`. This is an event stream that contains no gameplay relevant data (https://github.com/Blizzard/s2protocol/blob/ea1fe843b46ee5589a86054361d8d13e49483790/s2protocol/versions/protocol77661.py#L348-L354). I believe this file could be simply removed, and SC2 client should still allow to view the replay. Just without chat history, minimap pings etc.
> 
> If however I'm wrong about it, then another solution would be replacing this file with a one from another replay, which has no chat history. It might be important to use the same version. And preferably with the same amount of participating players.
> 
> In regards to re-encoding replays, yes it is possible. But it's out of the scope `sc2reader` - since it's a reader :) But Blizzard has released scripts for encoding in their repo: https://github.com/Blizzard/s2protocol/blob/ea1fe843b46ee5589a86054361d8d13e49483790/s2protocol/encoders.py
> It lacks documentation/code examples, but this is the way to go about this. And this is also how Deepmind anonymized replay packs with AlphaStar from ladder.
> 
> Also, if all you need is to hide the chat history. Then there's yet another method! :) You could modify the observer interface, and hide the part of the UI responsible for displaying messages.

Thanks, many solutions. I removed the message.events by mpqeditor and it worked.
