### ISSUE TITLE
Patch 5.0 Broke replay loading

### ISSUE THREAD

**Issue by georgh** [ggtracker/sc2reader#121]
Loading replays I get

`unpack requires a buffer of 4 bytes`

on line 91 in decoders.py.

**Comment by georgh** [comment]
I am not sure how to fix it - blizzard seemed to changed field # 69 
-> https://github.com/Blizzard/s2protocol/blob/master/s2protocol/versions/protocol81009.py
but I cant find where this needs change in screader

**Comment by Rairden** [comment]
I get the same error as you @georgh on line 91 in decoders.py
`struct.error: unpack requires a buffer of 4 bytes`

A real shame blizzard's patch broke sc2reader. I looked it up and sc2replaystats.com uses `sc2protocol` according to this reddit [thread](https://www.reddit.com/r/starcraft/comments/51dy8p/sc2_gamersprogrammers_im_looking_for_resources_to/d7bhc2p?utm_source=share&utm_medium=web2x).

I'll share 2 links to replays before/after the patch (7/10/2020 and 7/28/2020) that were uploaded to `sc2replaystats`. Their tool still successfully parses replay data:
https://sc2replaystats.com/replay/15337707
https://sc2replaystats.com/replay/15606794

**Comment by StoicLoofah** [comment]
Right, sc2replaystats uses https://github.com/Blizzard/s2protocol, and we also update sc2reader using the info from `s2protocol`. You can see a few examples of past pull requests to do the same using roughly the steps as described in https://github.com/GraylinKim/sc2reader/pull/187 

* Support for 77379 #106 
* Support for 75689 #95 
* Support for 70154 #68

If someone would like to step  up and make an equivalent pull request, that would be awesome. Otherwise, I'll shoot to get around to this by the weekend.

There's a related task as well to get new balance data (as seen in #107 and #100 via the instructions at https://github.com/ggtracker/sc2reader/blob/upstream/sc2reader/data/HOWTO.md ). Given the size of 5.0, I suspect that this will also be necessary.

**Comment by Talv** [comment]
I'll try to submit the fix later today.
