### ISSUE TITLE
DialogControlEvent usage...

### ISSUE THREAD

**Issue by Andrene** [ggtracker/sc2reader#144]
Hello, I'm trying to make use of the DialogControlEvent (it kinda exists... Its under readers, I just had to make a class for it.)
I think im not doing anything wrong, however I'm trying to see if a particular dialog item is pressed.
Currently I can see that a dialog item was pressed and its cid. However it looks like the cid may differ between games(maybe map versions?). I was wondering if anyone knows a way to determine the cid of a dialog item to hopefully alleviate this issue. 

For my DialogControlEvent class its pretty basic...
```python
class DialogControlEvent(GameEvent):
    def __init__(self, frame, pid, data):
        super(DialogControlEvent, self).__init__(frame,pid)
        self.data = data
        self.cid = data["control_id"]
        self.type = data["event_type"]
        self.eventdata = data["event_data"]
```
edit: I have no clue how to format that right on github :(

**Comment by cclauss** [comment]
> I have no clue how to format that right on github :(

https://docs.github.com/en/github/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks says:
\`\`\`python
Your code here.
\`\`\`

**Comment by Talv** [comment]
> Currently I can see that a dialog item was pressed and its cid. However it looks like the cid may differ between games(maybe map versions?).

It's entirely up to the map code which control gets what ID. SC2 assigns them incrementally, for every `*Create` or `*Hookup` action. I don't remember if the IDs get released when `*Destroy` is called, but if I were to guess I'd say no.

So yes, map versions may have effect on the ID, simply due to fact that map can introduce new controls that get created before the one you care about, and that will shift the IDs by X.

If the controls are part of some dynamic interface, that gets created and destroyed multiple times during the game, in response to something that happens in the game. Then it'll inevitably affect the IDs as well.

If you've control over the map code, then there are some tricks you can do to make it easier to "parse" such things - make it more explicit what ID corresponds to what Control from the replay events perspective. If you don't... then it doesn't leave you with much room to maneuver, at best you could make an educated guess in regards to the IDs, using your knowledge about the map.

**Comment by Andrene** [comment]
Thanks Talv, I don't have control over the map, however I can always ask/create an implementation so they just have to pop it in. Not sure what you mean/how to make it more explicit what ID corresponds to a Control. The button is just created using a Create Dialog Item Button.
