### ISSUE TITLE
Fetching custom game unit ID/Name

### ISSUE THREAD

**Issue by Andrene** [ggtracker/sc2reader#152]
I'm trying to parse replays for a custom game, however it seems to be only giving me data from based on the pre-loaded game data in "sc2reader/data/". For instance, custom abilities show with an id of 0, and custom units don't have a name/type associated with them.

I'm not too sure on how the data is loaded so that I can hack together a solution.. Any thoughts?

**Comment by StoicLoofah** [comment]
Not sure I have a good solution for that. Everything in `sc2reader/data/` is actually to some degree manually imported based on the sc2mod data for normal ladder matches, so it almost by design doesn't include custom games.

Sorry I don't have an obvious workaround, but perhaps someone else can jump in

**Comment by dsjoerg** [comment]
You can use the Blizzard/s2protocol repo. It’s lower level than sc2reader
but will expose all the raw data you want.

**Comment by Andrene** [comment]
I know, I'd just prefer a SC2Reader solution, even if I have to build it out. Mostly since i'm already using SC2Reader, and because I dont want to impact performance too much...

**Comment by Andrene** [comment]
After reading through a script making use of S2Protocol, it looks like the unit_type_name is only shown when a UnitBornEvent occurs. After a quick test the same is true of SC2Reader. While it would be nice to have that as part of the UnitDiedEvent, I can make do with what I've found.
