### ISSUE TITLE
We should start using releases

### ISSUE THREAD

**Issue by cclauss** [ggtracker/sc2reader#39]
https://github.com/ggtracker/sc2reader/releases is empty but the old repo used releases.

**Comment by dsjoerg** [comment]
@cclauss I would be happy to let you do this — is there anything I need to do to permit you to do this?

**Comment by cclauss** [comment]
IBM webcast just starting now that features sc2reader...

Use data science to up your game performance
Live On August 24, 2017 at 11am Eastern US (and again at 4pm Eastern)

https://developer.ibm.com/code/journey/analyze-starcraft-ii-replays-with-jupyter-notebooks/

**Comment by dsjoerg** [comment]
Where did you see this promoted / advertised?

**Comment by cclauss** [comment]
https://developer.ibm.com/code

**Comment by StoicLoofah** [comment]
With the powers vested in me by @dsjoerg, no open GitHub issues, a clean CircleCI, and no apparent gaps for MVP, I move to mark a sc2reader 1.0 release. Any objections?

Going forward, we should have regularly released versions. I propose that we use a standard semantic versioning https://semver.org/

Notably, I suggest we should generally use minor versions whenever blizzard releases new protocol versions since that is new functionality by supporting potentially new data.

What do you guys think?

**Comment by dsjoerg** [comment]
Amazing progress!

**Comment by StoicLoofah** [comment]
v1.0.0 is out

* https://github.com/ggtracker/sc2reader/releases/tag/v1.0.0
* https://pypi.org/project/sc2reader/

Help to keep me honest with future changes as well because I will probably forget to update versions
