### ISSUE TITLE
Vikings are being marked Neutral which screws up OwnershipTracker in TvT etc

### ISSUE THREAD

**Issue by dsjoerg** [ggtracker/sc2reader#5]
http://ggtracker.com/matches/2719434
There are vikings after the 30:00 mark but they don't show up in the graph,
because OwnershpTracker thinks nobody owns them, because

```
>>> replay.player[2].selection[32000][10].objects[1].name
'VikingAssault'
>>> replay.player[2].selection[32000][10].objects[1].race
'Neutral'
```

I see the issue has something to do with the unit list naming conventions in sc2reader/data/**init**.py, but I don't grok the code well enough to know which way to fix it.

And I see that graylinkim/sc2reader has moved forward to a newer approach, however unit_info.json may have the same issue.

**Comment by dsjoerg** [comment]
This one is pretty important in that every match with Vikings has the wrong army size chart.

**Comment by GraylinKim** [comment]
I'll get it fixed this afternoon.

**Comment by GraylinKim** [comment]
Okay, so we have a problem. I created a couple test replays to verify.

When targeting units the correct unit type (and mode) is recorded. If you attack a flying viking specifically then it'll be written as 72 (VikingFighter). If you attack a grounded viking then it'll be written as 71 (VikingAssault). This is true for SiegeTanks and WidowMines as well.

When selecting units, only one of the modes is recorded; regardless of the mode the unit is actually in. For widow mines and siege tanks it is using the normal form. For vikings (for some reason) it is using the Assault form. I've examined the actual event bits and confirmed that this is the case. Somewhat confusingly, alternate building forms (FactoryFlying, ObrtialCommand) still seem to be written out with the correct unit type.

Its not clear to me if this new selection event behavior is intended or not. Either way, it will make knowing the mode the unit is in unreliable going forward. We don't currently use this information, it seems like now we never will.

The issue that you observed is a result of us track one of the unit forms; we never implemented unit consolidation like sc2reader's new unit patch does. This change in selection event behavior actually improves the activity tracking for most units. Because we choose to track Viking (Flying) the patch made us lose total track of vikings.

The quick fix for the current patch is to just change the name of the army unit we track from Viking to VikingAssault. That would break viking tracking in all prior patches though. The harder fix is to pull the new unit patch in which treats all forms of a unit as the same unit. We could also try to perform our own consolidation somewhere in the activity plugin, I'm not sure if that would be easier or not.

What do you want to do? I'm available for a chat all night.

**Comment by dsjoerg** [comment]
Isnt there a simple change that fixes what we care about for the current
patch without breaking things for prev patches?

Will be online in abt 2 hrs.

On Apr 6, 2013, at 7:56 PM, Graylin Kim notifications@github.com wrote:

Okay, so we have a problem. I created a couple test replays to verify.

When targeting units the correct unit type (and more) is recorded. If you
attack a flying viking specifically then it'll be written as 72
(VikingFighter). If you attack a grounded viking then it'll be written as
71 (VikingAssault). This is true for SiegeTanks and WidowMines as well.

When selecting units, only one of the modes is recorded; regardless of the
mode the unit is actually in. For widow mines and siege tanks it is using
the normal form. For vikings (for some reason) it is using the Assault
form. I've examined the actual event bits and confirmed that this is the
case. Somewhat confusingly, alternate building forms (FactoryFlying,
ObrtialCommand) still seem to be written out with the correct unit type.

Its not clear to me if this new selection event behavior is intended or
not. Either way, it will make knowing the mode the unit is in unreliable
going forward. We don't currently use this information, it seems like now
we never will.

The issue that you observed is a result of us track one of the unit forms;
we never implemented unit consolidation like sc2reader's new unit patch
does. This change in selection event behavior actually improves the
activity tracking for most units. Because we choose to track Viking
(Flying) the patch made us lose total track of vikings.

The quick fix for the current patch is to just change the name of the army
unit we track from Viking to VikingAssault. That would break viking
tracking in all prior patches though. The harder fix is to pull the new
unit patch in which treats all forms of a unit as the same unit. We could
also try to perform our own consolidation somewhere in the activity plugin,
I'm not sure if that would be easier or not.

What do you want to do? I'm available for a chat all night.

—
Reply to this email directly or view it on
GitHubhttps://github.com/ggtracker/sc2reader/issues/5#issuecomment-16006460
.

**Comment by GraylinKim** [comment]
I've tested with Zerg and everything is as it was before. Burrowed Zerglings are still ZerglingBurrowed, Baneling cocoons are still BanelingCocoon, and uprooted Spine Crawlers are still SpineCrawlerUprooted.

Warp Prisms, Thors (2 modes now), and Hellions (2 modes now) all have this new behavior though. I think that accounts for all units with different modes.

Yes, we can do a switch on the new version for a quick patch. I'll look into it now.

**Comment by GraylinKim** [comment]
I've looked into the history of this and the change came with the 2.0.0 release during the HotS Beta. I'll be back around 10.

**Comment by GraylinKim** [comment]
Okay, I looked at a few different options but I think that c37df7f329386d9b67eda7f677103dad5bd516aa represents the smallest possible change to make this work for now. I've confirmed the new behaviour on the example posted above.

**Comment by dsjoerg** [comment]
Since when are you British?!?

**Comment by dsjoerg** [comment]
Sweeeeet that certainly looks like a well-targeted patch :)
I'll push it out to production tonight.  Thank you!

**Comment by GraylinKim** [comment]
Apparently the auto correct on my browser is.

**Comment by dsjoerg** [comment]
Excellent, thanks!
